/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#6c2106",
        "tertiary-container": "#f38764",
        "primary-fixed-dim": "#4fdbc8",
        "surface-bright": "#29385c",
        "surface-container-highest": "#243457",
        "on-primary-container": "#00423b",
        "on-primary": "#003731",
        "secondary-fixed": "#bbece2",
        background: "#001234",
        "surface-container-low": "#081a3c",
        "inverse-primary": "#006b5f",
        surface: "#001234",
        "primary-container": "#14b8a6",
        "on-tertiary-fixed-variant": "#7c2d11",
        "tertiary-fixed": "#ffdbd0",
        "on-background": "#d9e2ff",
        "on-secondary-fixed": "#00201c",
        "inverse-on-surface": "#202f52",
        "on-secondary-fixed-variant": "#1f4e47",
        "on-primary-fixed": "#00201c",
        "primary-fixed": "#71f8e4",
        "surface-container-high": "#19294b",
        "outline-variant": "#3c4947",
        tertiary: "#ffb59e",
        "surface-container": "#0d1e40",
        "tertiary-fixed-dim": "#ffb59e",
        "surface-container-lowest": "#000d2a",
        "on-secondary-container": "#92c2b8",
        "on-tertiary-fixed": "#3a0b00",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-surface-variant": "#bbcac6",
        "on-secondary": "#003731",
        "surface-tint": "#4fdbc8",
        "secondary-fixed-dim": "#a0d0c6",
        outline: "#859490",
        "secondary-container": "#21514a",
        primary: "#4fdbc8",
        "on-primary-fixed-variant": "#005048",
        "surface-variant": "#243457",
        error: "#ffb4ab",
        secondary: "#a0d0c6",
        "surface-dim": "#001234",
        "on-tertiary": "#5e1800",
        "on-surface": "#d9e2ff",
        "inverse-surface": "#d9e2ff",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      boxShadow: {
        softGlow: "0 0 40px rgba(20, 184, 166, 0.3)",
      },
    },
  },
  plugins: [],
};
